src/main/java/org/spongepowered/api/Server.java
src/main/java/org/spongepowered/api/util/gen/BiomeArea.java
src/main/java/org/spongepowered/api/util/gen/BlockBuffer.java
src/main/java/org/spongepowered/api/util/gen/ImmutableBiomeArea.java
src/main/java/org/spongepowered/api/util/gen/ImmutableBlockBuffer.java
src/main/java/org/spongepowered/api/util/gen/MutableBiomeArea.java
src/main/java/org/spongepowered/api/util/gen/MutableBlockBuffer.java
src/main/java/org/spongepowered/api/util/gen/package-info.java
src/main/java/org/spongepowered/api/world/Chunk.java
src/main/java/org/spongepowered/api/world/World.java
src/main/java/org/spongepowered/api/world/gen/BiomeGenerator.java
src/main/java/org/spongepowered/api/world/gen/Populator.java
src/main/java/org/spongepowered/api/world/gen/WorldGenerator.java

Here are changes resultant of a discussion on IRC relating to the recent commit e93c0919e0bf4.
List of changes:
- `Server#createWorld` changed to not return an Optional, and additional versions created
- `BiomeManager` was renamed `BiomeGenerator`, and was functionally modified.
- `BiomeArea` was created to represent an area of biomes, mutable and immutable versions were also created.
- `BlockBuffer` was modified to use `BlockState` rather than `BlockType` to support metadata values.
- `BiomeVolume` was reworked to return a `BiomeType` rather than a `Biome`, and to include a setter for biomes.
- `Biome` was removed.
- `Populator` was modified to take a `Chunk` rather than a `MutableBlockBuffer`.
- `WorldGenerator` was clarified.
- `World` was modified to remove the `getBiomeManger` method …

Discussed changes for the World Generation API

---

src/main/java/org/spongepowered/api/service/scheduler/Scheduler.java

The API version is not synced as the currently available API version
in the implementation. The SpongeAPI submodule is buried.  Hoping to
lift it up as the current version for subsequent builds.

Fix branch hiccup

---

src/main/java/org/spongepowered/api/Game.java
src/main/java/org/spongepowered/api/GameRegistry.java
src/main/java/org/spongepowered/api/GameVersion.java
src/main/java/org/spongepowered/api/Server.java
src/main/java/org/spongepowered/api/entity/player/User.java
src/main/java/org/spongepowered/api/event/server/StatusPingEvent.java
src/main/java/org/spongepowered/api/status/Favicon.java
src/main/java/org/spongepowered/api/status/PlayerProfile.java
src/main/java/org/spongepowered/api/status/StatusClient.java
src/main/java/org/spongepowered/api/status/StatusResponse.java

Adds an API for #331 to the SpongeAPI. This implements most things mentioned there except direct access to protocol versions, instead there is a (currently) read-only wrapper around them as `GameVersion`.
I decided to use the newer names from the protocol rewrite in 1.7 instead of the older names from the legacy ping. That's why "server list ping" is "status ping" and "MotD" is "description" now. This matches these names to the ones used in the protocol and the Minecraft source, and should also prevent confusion about "MotD" in the server list, or "MotD" as the message if you join a server (like used by Essentials) in the future.

Server Status Ping API

---

src/main/java/org/spongepowered/api/GameRegistry.java

Fixes #408 
Instead of using List, use Collection which can return a `Set` or `List` or whatever needed.

Change GameRegistry returns from List to Collection.

---

src/main/java/org/spongepowered/api/event/entity/EntityExplosionEvent.java
src/main/java/org/spongepowered/api/event/entity/ExplosionPrimeEvent.java

Adds two new events to specifically deal with explosives. Fixes #416 
**EntityExplosionEvent**
Is designed for when an explosive entity has detonated and is about to change blocks in the world. 
**ExplosionPrimeEvent**
Is designed for when an explosive entity is primed to detonate (pre-explosion).

Add explosion events

---

src/main/java/org/spongepowered/api/entity/living/Living.java
src/main/java/org/spongepowered/api/event/SpongeEventFactory.java
src/main/java/org/spongepowered/api/event/entity/EntityEnterPortalEvent.java
src/main/java/org/spongepowered/api/event/entity/EntityExitPortalEvent.java
src/main/java/org/spongepowered/api/event/entity/EntityIgniteEvent.java
src/main/java/org/spongepowered/api/event/entity/EntityInteractEvent.java
src/main/java/org/spongepowered/api/event/entity/EntityMoveEvent.java
src/main/java/org/spongepowered/api/event/entity/EntityPotionEffectChangeEvent.java
src/main/java/org/spongepowered/api/event/entity/EntityTameEvent.java
src/main/java/org/spongepowered/api/event/entity/EntityTeleportEvent.java
src/main/java/org/spongepowered/api/event/entity/EntityUnleashEvent.java
src/main/java/org/spongepowered/api/event/entity/ExplosionPrimeEvent.java
src/main/java/org/spongepowered/api/potion/PotionEffect.java
src/main/java/org/spongepowered/api/world/biome/BiomeType.java

Achieves the following from the OCD list #221.
Fixes #462

Add more entity related events. Enhance several entity related events. 

---

src/main/java/org/spongepowered/api/service/persistence/DataSerializableBuilder.java
src/main/java/org/spongepowered/api/service/persistence/DataSource.java
src/main/java/org/spongepowered/api/service/persistence/DataSourceFactory.java
src/main/java/org/spongepowered/api/service/persistence/InvalidDataException.java
src/main/java/org/spongepowered/api/service/persistence/SerializationService.java
src/main/java/org/spongepowered/api/service/persistence/data/DataQuery.java
src/main/java/org/spongepowered/api/service/persistence/data/DataView.java
src/main/java/org/spongepowered/api/service/persistence/data/MemoryDataContainer.java
src/main/java/org/spongepowered/api/service/persistence/data/MemoryDataView.java
src/main/java/org/spongepowered/api/util/Coerce.java
src/test/java/org/spongepowered/api/service/persistence/data/MemoryDataTest.java
src/test/java/org/spongepowered/api/service/persistence/data/SimpleDataBuilder.java
src/test/java/org/spongepowered/api/service/persistence/data/SimpleDataSerializable.java
src/test/java/org/spongepowered/api/util/CoerceTest.java

This implements the commonly used [`DataView`](https://github.com/SpongePowered/SpongeAPI/blob/feature/persistence-memory/src/main/java/org/spongepowered/api/service/persistence/data/DataView.java) as a usable data structure that can be used by both implementation and plugins alike. 
This also expands on the Persistence API by creating a usable `SerializationService` that enables the registration of custom serialization for various `DataSerializable`s, this allows for implementations to register `DataSerializableBuilder`s for various things like `ItemStack`s, `Entity`, etc. This can also be used by plugins to enable serialization and deserialization of their own `DataSerializable`s.
Design Proposal for a usable Persistence API
----------------
Many developers have been eager to use …

Expand Persistence API

---

src/main/java/org/spongepowered/api/entity/projectile/DamagingProjectile.java

This PR allows `DamagingProjectile`s to deal variable amounts of damage, depending on the entity hit. An example of this behavior in Vanilla is a blaze taking damage from snowballs, which ordinarily deal no damage.
I've also fixed some minor javadoc issues in `getDamage` and `setDamage`.
This resolves https://github.com/SpongePowered/SpongeAPI/issues/399

Add variable damage amounts to DamagingProjectile

---

build.gradle

This adds 2 new dependencies to SpongeAPI (primarily for plugin authors to use). The distribution of our both implementations will not be affected by this. Both dependencies are already included in Minecraft so this just exposes them to plugin developers.
- **GSON:** As a JSON dependency, see #625. While some may prefer another library to work with JSON (e.g. Jackson), GSON is already included in Minecraft and so we don't need to bundle anything additional. Plugin authors can still bundle an alternative library to work with JSON.
- **commons-lang3:** I'm not completely sure if we should provide this. It contains quite a lot of utilities which make stuff easier to use, and given its size (~600 KB) it would be stupid if plugin developers would need to bundle it (without a dependency in …

Add GSON and commons-lang3 to dependencies

---

src/main/java/org/spongepowered/api/util/command/CommandCallable.java
src/main/java/org/spongepowered/api/util/command/dispatcher/SimpleDispatcher.java

This is a proposed fix to #645.
Since `Optional<T>` is invariant (this is Java, after all), we need to specify a wildcard generic type `Optional<? extends T>` for text methods. I don't know of any other solution, but am unsure that this is the only one which is why I am making such a small PR.
This is probably required for other places, but this is a hotfix for just the scope of the mentioned issue.

Make Optional<Text> returns support subtypes of Text in CommandCallable methods

---

src/main/java/org/spongepowered/api/event/Event.java
src/main/java/org/spongepowered/api/event/SpongeEventFactory.java
src/main/java/org/spongepowered/api/util/annotation/ImplementedBy.java
src/main/java/org/spongepowered/api/util/event/factory/AnnotationEventFactoryPlugin.java
src/main/java/org/spongepowered/api/util/event/factory/ClassGenerator.java
src/main/java/org/spongepowered/api/util/event/factory/EventFactoryPlugin.java
src/main/java/org/spongepowered/api/util/event/superclasses/AbstractBulkBlockEvent.java
src/main/java/org/spongepowered/api/util/event/superclasses/package-info.java
src/main/java/org/spongepowered/api/util/reflect/AccessorFirstStrategy.java
src/main/java/org/spongepowered/api/util/reflect/Property.java
src/test/java/org/spongepowered/api/event/SpongeEventFactoryTest.java

This PR makes a number of (interrelated) improvements to the event generation system:
* Previously, for methods overridden by other interfaces (think `getEntity`, `getLiving`, `getHuman`, etc), only one accessor and mutator would be generated. Due to the confusing way in which java determines which return type would be used, the method called wouldn't always be implemented. This PR generates accessors and mutators for all overridden methods - using only one field.
* Instead of having all generated event classes extend from `AbstractEvent`, the base class can be specified using the new `@ImplementedBy` annotation, or the event generator plugin system. This is used to implement methods which don't conform to the accessor/mutator pattern expected by the class generator (`getXXX`, `setXXX`, …

Rework event generation

---

src/main/java/org/spongepowered/api/Game.java
src/main/java/org/spongepowered/api/Platform.java

Intended as a fix for #644.
This PR abstracts away implementation and platform-specific information about the game into a Platform class. It also moves the current Platform enum to Platform.Side. 
I know @Minecrell had some additional ideas for keys.

Add Platform interface

---

src/main/java/org/spongepowered/api/event/SpongeEventFactory.java
src/main/java/org/spongepowered/api/event/network/ConnectEvent.java
src/main/java/org/spongepowered/api/event/network/DisconnectEvent.java
src/main/java/org/spongepowered/api/event/network/GameClientAuthEvent.java
src/main/java/org/spongepowered/api/event/network/GameClientConnectEvent.java
src/main/java/org/spongepowered/api/event/network/GameClientLoginEvent.java
src/main/java/org/spongepowered/api/event/rcon/RconLoginEvent.java
src/main/java/org/spongepowered/api/event/rcon/RconQuitEvent.java

Fired before `PlayerJoinEvent`, other players will not know the player attempted to join if the event is cancelled.
No longer modelling around `FMLNetworkEvent.ServerConnectionFromClientEvent`, `PlayerConnectEvent` will occur before FML initializes it's handshake.
Renamed to `ClientConnectEvent`

Add ClientConnectEvent, for when a player initially connects to the server

---

src/main/java/org/spongepowered/api/data/DataTransactionResult.java
src/main/java/org/spongepowered/api/data/manipulator/immutable/common/AbstractImmutableBooleanData.java
src/main/java/org/spongepowered/api/data/manipulator/immutable/common/AbstractImmutableBoundedComparableData.java
src/main/java/org/spongepowered/api/data/manipulator/immutable/common/AbstractImmutableData.java
src/main/java/org/spongepowered/api/data/manipulator/immutable/common/AbstractImmutableSingleCatalogData.java
src/main/java/org/spongepowered/api/data/manipulator/immutable/common/AbstractImmutableSingleData.java
src/main/java/org/spongepowered/api/data/manipulator/immutable/common/AbstractImmutableSingleEnumData.java
src/main/java/org/spongepowered/api/data/manipulator/immutable/common/collection/AbstractImmutableSingleListData.java
src/main/java/org/spongepowered/api/data/manipulator/immutable/common/collection/AbstractImmutableSingleMapData.java
src/main/java/org/spongepowered/api/data/manipulator/immutable/common/collection/AbstractImmutableSingleSetData.java
src/main/java/org/spongepowered/api/data/manipulator/immutable/common/collection/package-info.java
src/main/java/org/spongepowered/api/data/manipulator/immutable/common/package-info.java
src/main/java/org/spongepowered/api/data/manipulator/mutable/common/AbstractBooleanData.java
src/main/java/org/spongepowered/api/data/manipulator/mutable/common/AbstractBoundedComparableData.java
src/main/java/org/spongepowered/api/data/manipulator/mutable/common/AbstractData.java
src/main/java/org/spongepowered/api/data/manipulator/mutable/common/AbstractIntData.java
src/main/java/org/spongepowered/api/data/manipulator/mutable/common/AbstractSingleCatalogData.java
src/main/java/org/spongepowered/api/data/manipulator/mutable/common/AbstractSingleData.java
src/main/java/org/spongepowered/api/data/manipulator/mutable/common/AbstractSingleEnumData.java
src/main/java/org/spongepowered/api/data/manipulator/mutable/common/collection/AbstractSingleListData.java
src/main/java/org/spongepowered/api/data/manipulator/mutable/common/collection/AbstractSingleMapData.java
src/main/java/org/spongepowered/api/data/manipulator/mutable/common/collection/AbstractSingleSetData.java
src/main/java/org/spongepowered/api/data/manipulator/mutable/common/collection/package-info.java
src/main/java/org/spongepowered/api/data/manipulator/mutable/common/package-info.java

With the stability of abstract `DataManipulator` implementation in SpongeCommon, I feel it's safe to now supply these abstractions for plugin usage. Little should change at this point.

Supply Abstract Data implementations for Plugin usability

---

src/main/java/org/spongepowered/api/Platform.java
src/main/java/org/spongepowered/api/plugin/PluginContainer.java

This extends the Platform API by replacing specific methods like `getName()` or `getApiVersion()` with an exposed `PluginContainer` for the API and the implementation, which provides all of these methods and possibly more in the future (as soon we have added more [plugin metadata](https://github.com/SpongePowered/SpongeAPI/issues/822)).
This also matches the current design in SpongeVanilla and Forge where the components of the implementation (e.g. Minecraft, Forge, SpongeForge) are all represented as separate plugins, even though they aren't standalone plugins.
SpongeCommon PR: https://github.com/SpongePowered/SpongeCommon/pull/277
SpongeVanilla PR: https://github.com/SpongePowered/SpongeVanilla/pull/187
SpongeForge PR: https://github.com/SpongePowered/SpongeForge/pull/423

Extend platform API

---

src/main/java/org/spongepowered/api/data/Queries.java
src/main/java/org/spongepowered/api/data/key/Keys.java
src/main/java/org/spongepowered/api/data/manipulator/catalog/CatalogItemData.java
src/main/java/org/spongepowered/api/data/manipulator/immutable/ImmutableColoredData.java
src/main/java/org/spongepowered/api/data/manipulator/mutable/ColoredData.java
src/main/java/org/spongepowered/api/data/manipulator/mutable/tileentity/BannerData.java
src/main/java/org/spongepowered/api/data/type/DyeColor.java
src/main/java/org/spongepowered/api/effect/particle/ColoredParticle.java
src/main/java/org/spongepowered/api/effect/particle/ParticleEffect.java
src/main/java/org/spongepowered/api/effect/particle/ParticleType.java
src/main/java/org/spongepowered/api/item/FireworkEffect.java
src/main/java/org/spongepowered/api/text/format/TextColor.java
src/main/java/org/spongepowered/api/text/format/TextColors.java
src/main/java/org/spongepowered/api/util/Color.java
src/test/java/org/spongepowered/api/util/ColorTest.java

Currently, the API uses `java.awt.Color` due to it's useful capabilities, however, the issue with it is that it's not stable in that it can not be translated to and from various other types of colors that are and will be exposed in the API. This includes `DyeColor` and soon `MapColor`. The benefit of this is that we have a final class `Color` that provides not only some translations between `java.awt.Color`, but also adds some static methods for usability.

Replace the use of java.awt.Color with our own Color

---

src/main/java/org/spongepowered/api/event/filter/IsCancelled.java
src/main/java/org/spongepowered/api/event/filter/cause/All.java
src/main/java/org/spongepowered/api/event/filter/cause/First.java
src/main/java/org/spongepowered/api/event/filter/cause/Last.java
src/main/java/org/spongepowered/api/event/filter/cause/Root.java
src/main/java/org/spongepowered/api/event/filter/cause/package-info.java
src/main/java/org/spongepowered/api/event/filter/data/Has.java
src/main/java/org/spongepowered/api/event/filter/data/Supports.java
src/main/java/org/spongepowered/api/event/filter/data/package-info.java
src/main/java/org/spongepowered/api/event/filter/package-info.java
src/main/java/org/spongepowered/api/event/filter/type/Exclude.java
src/main/java/org/spongepowered/api/event/filter/type/Include.java
src/main/java/org/spongepowered/api/event/filter/type/package-info.java

[Impl](https://github.com/SpongePowered/SpongeCommon/pull/274)
This branch adds annotation based event filtering to assist with reducing the amount of boilerplate necessary while writing event listeners.
These filters are applied to the method and apply a range of filters based on the event object.
This annotation allows you to listen to a supertype event (such as EntityEvent) and filter it to only receive a specified subset of the event type's subclasses.
```java
@Listener
@Include({ InteractBlockEvent.Secondary.class })
public void include(InteractBlockEvent event) {
// This listener will only fire if the event is one of the included types
}
```
The opposite of include, this allows you to listen to a supertype event and filter it to not receive a specified subset of the event type's …

[WIP] Add Event Filters

---

src/main/java/org/spongepowered/api/data/key/Keys.java
src/main/java/org/spongepowered/api/data/manipulator/immutable/ImmutableDisplayNameData.java
src/main/java/org/spongepowered/api/data/manipulator/immutable/entity/ImmutableCustomNameVisibleData.java
src/main/java/org/spongepowered/api/data/manipulator/mutable/entity/CustomNameVisibleData.java

[**API**](https://github.com/SpongePowered/SpongeAPI/pull/1013) | [Common](https://github.com/SpongePowered/SpongeCommon/pull/403)
This moves the `customNameVisible` method from `DisplayNameData` to the new `CustomNameData`, and renames the associated `Key`.

Add CustomNameData

---

src/main/java/org/spongepowered/api/world/extent/BiomeArea.java
src/main/java/org/spongepowered/api/world/extent/BlockVolume.java
src/main/java/org/spongepowered/api/world/extent/Extent.java
src/main/java/org/spongepowered/api/world/extent/ImmutableBiomeArea.java
src/main/java/org/spongepowered/api/world/extent/ImmutableBlockVolume.java
src/main/java/org/spongepowered/api/world/extent/InteractableVolume.java
src/main/java/org/spongepowered/api/world/extent/MutableBiomeArea.java
src/main/java/org/spongepowered/api/world/extent/MutableBlockVolume.java
src/main/java/org/spongepowered/api/world/extent/TileEntityVolume.java
src/main/java/org/spongepowered/api/world/extent/UnmodifiableBiomeArea.java
src/main/java/org/spongepowered/api/world/extent/UnmodifiableBlockVolume.java
src/main/java/org/spongepowered/api/world/extent/worker/BiomeAreaWorker.java
src/main/java/org/spongepowered/api/world/extent/worker/BlockVolumeWorker.java
src/main/java/org/spongepowered/api/world/extent/worker/MutableBiomeAreaWorker.java
src/main/java/org/spongepowered/api/world/extent/worker/MutableBlockVolumeWorker.java
src/main/java/org/spongepowered/api/world/extent/worker/package-info.java
src/main/java/org/spongepowered/api/world/extent/worker/procedure/BiomeAreaFiller.java
src/main/java/org/spongepowered/api/world/extent/worker/procedure/BiomeAreaMapper.java
src/main/java/org/spongepowered/api/world/extent/worker/procedure/BiomeAreaMerger.java
src/main/java/org/spongepowered/api/world/extent/worker/procedure/BiomeAreaReducer.java
src/main/java/org/spongepowered/api/world/extent/worker/procedure/BiomeAreaVisitor.java
src/main/java/org/spongepowered/api/world/extent/worker/procedure/BlockVolumeFiller.java
src/main/java/org/spongepowered/api/world/extent/worker/procedure/BlockVolumeMapper.java
src/main/java/org/spongepowered/api/world/extent/worker/procedure/BlockVolumeMerger.java
src/main/java/org/spongepowered/api/world/extent/worker/procedure/BlockVolumeReducer.java
src/main/java/org/spongepowered/api/world/extent/worker/procedure/BlockVolumeVisitor.java
src/main/java/org/spongepowered/api/world/extent/worker/procedure/package-info.java

An API for functional operations on BiomeArea, BlockVolume and their subtypes. Multithreaded support to follow (for thread-safe buffers).
Implemented here: https://github.com/SpongePowered/SpongeCommon/pull/423

Add view worker API

---

src/main/java/org/spongepowered/api/GameRegistry.java
src/main/java/org/spongepowered/api/data/key/Keys.java
src/main/java/org/spongepowered/api/extra/fluid/FluidStack.java
src/main/java/org/spongepowered/api/extra/fluid/FluidStackSnapshot.java
src/main/java/org/spongepowered/api/extra/fluid/FluidType.java
src/main/java/org/spongepowered/api/extra/fluid/FluidTypes.java
src/main/java/org/spongepowered/api/extra/fluid/data/manipulator/immutable/ImmutableFluidItemData.java
src/main/java/org/spongepowered/api/extra/fluid/data/manipulator/immutable/ImmutableFluidTankData.java
src/main/java/org/spongepowered/api/extra/fluid/data/manipulator/immutable/package-info.java
src/main/java/org/spongepowered/api/extra/fluid/data/manipulator/mutable/FluidItemData.java
src/main/java/org/spongepowered/api/extra/fluid/data/manipulator/mutable/FluidTankData.java
src/main/java/org/spongepowered/api/extra/fluid/data/manipulator/mutable/package-info.java
src/main/java/org/spongepowered/api/extra/fluid/data/package-info.java
src/main/java/org/spongepowered/api/extra/fluid/data/property/FluidTemperatureProperty.java
src/main/java/org/spongepowered/api/extra/fluid/data/property/FluidViscosityProperty.java
src/main/java/org/spongepowered/api/extra/fluid/data/property/package-info.java
src/main/java/org/spongepowered/api/extra/fluid/package-info.java

SpongeAPI | [SpongeCommon](https://github.com/SpongePowered/SpongeCommon/pull/410) | [SpongeForge](https://github.com/SpongePowered/SpongeForge/pull/489)
Forge has a Fluid API system that mods use to interact with each other for various purposes, and this exposes that system with the Data API. Plugins will be able to interact and interface with `TileEntity` based `IFluidHandler`s and `IFluidContainerItem`s.
The API itself was aided with @diesieben07's comments, and likewise the implementation of this will rely on Forge, with SpongeCommon providing some interfacing with vanilla based containers (namely buckets and such).

Add Fluid API representation

---

src/main/java/org/spongepowered/api/effect/sound/PitchModulation.java

Example usage:
```java
world.playSound(SoundType.NOTE_PIANO, position, 1, Pitch.C1);
```
will play a middle C.
Signed-off-by: Walker Crouse <walkercrouse@hotmail.com>

Add PitchModulation for sound effects

---

src/main/java/org/spongepowered/api/entity/living/Humanoid.java
src/main/java/org/spongepowered/api/entity/living/player/Player.java
src/main/java/org/spongepowered/api/item/inventory/Container.java
src/main/java/org/spongepowered/api/item/inventory/type/Interactable.java
src/main/java/org/spongepowered/api/item/inventory/type/TileEntityInventory.java

Common PR: https://github.com/SpongePowered/SpongeCommon/pull/501
The reason for this change is for clarity in the API. To say that a humanoid "views" an inventory or an entity can "interact" with a container is misleading: these are properties of a client connection. I am not saying that Humanoids or other entities should not have inventories, I have no qualms about that.
Pinging @Mumfrey 
Signed-off-by: Walker Crouse <walkercrouse@hotmail.com>

Humanoids do not have clients therefore they cannot "view" inventories or "interact" with things

---

build.gradle
gradle/sponge.gradle
src/ap/java/org/spongepowered/plugin/processor/AnnotationWrapper.java
src/ap/java/org/spongepowered/plugin/processor/PluginElement.java
src/ap/java/org/spongepowered/plugin/processor/PluginProcessExeption.java
src/ap/java/org/spongepowered/plugin/processor/PluginProcessor.java
src/ap/resources/META-INF/services/javax.annotation.processing.Processor
src/main/java/org/spongepowered/api/plugin/Dependency.java
src/main/java/org/spongepowered/api/plugin/Plugin.java
src/main/java/org/spongepowered/api/plugin/PluginContainer.java
src/main/java/org/spongepowered/api/plugin/PluginManager.java

This pull request extends the `@Plugin` annotation with several new fields for additional plugin metadata and adds an annotation processor for the `@Plugin` annotation which generates a `mcmod.info` file based on the values of the `@Plugin` annotation.
**Additions for plugin metadata:** (for #822)
- Description
- URL
- Plugin authors
- Simplified dependency syntax
Example for new dependency syntax:
```java
@Plugin(id = "net.minecrell.testplugin", dependencies = {
// Require WorldEdit to be loaded before plugin is constructed
@Dependency(id = "com.sk89q.worldedit"),
// Load updatifier first if it is present
@Dependency(id = "me.flibio.updatifier", optional = true)
})
```
As discussed in #624, this implements `mcmod.info` as the format for plugin metadata in the JAR file. This is how it …

Extend plugin metadata

---

src/main/java/org/spongepowered/api/data/Queries.java
src/main/java/org/spongepowered/api/text/Text.java
src/main/java/org/spongepowered/api/text/TextElement.java
src/main/java/org/spongepowered/api/text/TextRepresentable.java
src/main/java/org/spongepowered/api/text/TextTemplate.java
src/main/java/org/spongepowered/api/text/TextTemplateArgumentException.java
src/main/java/org/spongepowered/api/text/action/ClickAction.java
src/main/java/org/spongepowered/api/text/action/HoverAction.java
src/main/java/org/spongepowered/api/text/channel/MessageReceiver.java
src/main/java/org/spongepowered/api/text/format/TextColor.java
src/main/java/org/spongepowered/api/text/format/TextFormat.java
src/main/java/org/spongepowered/api/text/format/TextStyle.java
src/main/java/org/spongepowered/api/text/serializer/TextConfigSerializer.java
src/main/java/org/spongepowered/api/text/serializer/TextTemplateConfigSerializer.java
src/main/java/org/spongepowered/api/text/transform/DynamicPartitionedTextFormatter.java
src/main/java/org/spongepowered/api/text/transform/FixedPartitionedTextFormatter.java
src/main/java/org/spongepowered/api/text/transform/PartitionedTextFormatter.java
src/main/java/org/spongepowered/api/text/transform/SimpleTextFormatter.java
src/main/java/org/spongepowered/api/text/transform/SimpleTextTemplateApplier.java
src/main/java/org/spongepowered/api/text/transform/TextFormatter.java
src/main/java/org/spongepowered/api/text/transform/TextTemplateApplier.java

This PR adds re-usable, serializable, text templates to SpongeAPI. This is useful in plugin development when a developer wishes to store a message in a config file with variable elements.
```java
import static org.spongepowered.api.text.template.TextTemplate.*;
TextTemplate template = of(
TextColors.BLUE, "Hello, ", arg("playerName").color(TextColors.AQUA).style(TextStyles.BOLD), "!"
);
void onPlayerJoin() {
player.sendMessage(template, ImmutableMap.of("playerName", Text.of(player.getName()));
}
```
A few things to note:
* Repeated arguments are permitted but must be "equivalent", meaning that if argument 1 named 'x' is optional argument 2 named 'x' must also be optional.
* Elements are appended to the text builder in the order in which they appear.
* Arguments are required by default. …

TextTemplate API

---

src/main/java/org/spongepowered/api/entity/living/player/Player.java

This PR changes `openInventory` and `closeInventory` to require ` Cause`. When these methods are implemented, the provided `Cause` will be used when firing `InteractInventoryEvent.<Open/Close>`

Require a Cause when opening or closing an inventory

---

src/main/java/org/spongepowered/api/GameRegistry.java
src/main/java/org/spongepowered/api/item/inventory/ItemStack.java
src/main/java/org/spongepowered/api/item/inventory/ItemStackBuilderPopulators.java
src/main/java/org/spongepowered/api/item/inventory/ItemStackGenerator.java
src/main/java/org/spongepowered/api/item/inventory/generation/TestItemGenrator.java
src/main/java/org/spongepowered/api/item/inventory/generation/package-info.java
src/main/java/org/spongepowered/api/item/merchant/TradeOffer.java
src/main/java/org/spongepowered/api/item/merchant/TradeOfferGenerator.java
src/main/java/org/spongepowered/api/item/merchant/TradeOfferListMutator.java
src/main/java/org/spongepowered/api/item/merchant/VillagerRegistry.java
src/main/java/org/spongepowered/api/util/weighted/WeightedTable.java

This adds some dynamic "recipe" generators that can be used to not only generate `ItemStack`s and `TradeOffer`s. Namely, this adds `TradeOfferGenerator`s to be used and queried for with `Villager` `Career`s.
Granted, there was #662, but I feel that with the various "chance" utils introduced from #734 can be of better use and instead of adding new interfaces to populate an `ItemStack.Builder`, when a `BiConsumer` is perfectly acceptable, and not only does it achieve full customizability, but it's base intentions are to make semi-random generation simple. @Deamon5550 mentioned he'd be adding some utility methods to `WeightedTable` so that some cases where the `WeightedTable` does not have to be re-created every single invocation of `BiConsumer.apply` for the various …

[WIP] ItemStack and TradeOffer Generators

---

src/main/java/org/spongepowered/api/command/source/CommandBlockSource.java
src/main/java/org/spongepowered/api/data/key/Keys.java
src/main/java/org/spongepowered/api/data/manipulator/immutable/ImmutableCommandData.java
src/main/java/org/spongepowered/api/data/manipulator/immutable/ImmutableMobSpawnerData.java
src/main/java/org/spongepowered/api/data/manipulator/mutable/CommandData.java
src/main/java/org/spongepowered/api/entity/vehicle/minecart/ChestMinecart.java
src/main/java/org/spongepowered/api/entity/vehicle/minecart/CommandBlockMinecart.java
src/main/java/org/spongepowered/api/entity/vehicle/minecart/ContainerMinecart.java
src/main/java/org/spongepowered/api/entity/vehicle/minecart/FurnaceMinecart.java
src/main/java/org/spongepowered/api/entity/vehicle/minecart/HopperMinecart.java
src/main/java/org/spongepowered/api/entity/vehicle/minecart/MobSpawnerMinecart.java
src/main/java/org/spongepowered/api/entity/vehicle/minecart/RideableMinecart.java
src/main/java/org/spongepowered/api/entity/vehicle/minecart/TNTMinecart.java

[**API**](https://github.com/SpongePowered/SpongeAPI/pull/1113) | [Common](https://github.com/SpongePowered/SpongeCommon/pull/549)
This PR changes all of the Minecart entities to be appended with `Minecart` instead of pre-pended: `HopperMinecart` instead of `MinecartHopper`.
This is a difference compared to the rest of the API - for example: `Fireball` & `LargeFireball`, etc

Append 'Minecart' to names instead of prepending

---

src/main/java/org/spongepowered/api/profile/GameProfileCache.java
src/main/java/org/spongepowered/api/profile/GameProfileManager.java
src/main/java/org/spongepowered/api/profile/package-info.java

[**API**](https://github.com/SpongePowered/SpongeAPI/pull/1068) | [Common](https://github.com/SpongePowered/SpongeCommon/pull/495)
This introduces a replaceable `GameProfileCache` that is used (internally) for resolving profiles and profile related data.

Introduce GameProfileCache, and extract existing cache method to it

---

src/main/java/org/spongepowered/api/data/DataTransactionResult.java
src/main/java/org/spongepowered/api/data/key/Keys.java
src/main/java/org/spongepowered/api/data/manipulator/catalog/CatalogEntityData.java
src/main/java/org/spongepowered/api/data/manipulator/immutable/entity/ImmutableExplosionRadiusData.java
src/main/java/org/spongepowered/api/data/manipulator/mutable/entity/ExplosionRadiusData.java
src/main/java/org/spongepowered/api/data/manipulator/mutable/entity/FuseData.java
src/main/java/org/spongepowered/api/entity/EnderCrystal.java
src/main/java/org/spongepowered/api/entity/explosive/Explosive.java
src/main/java/org/spongepowered/api/entity/explosive/FusedExplosive.java
src/main/java/org/spongepowered/api/entity/living/monster/Creeper.java
src/main/java/org/spongepowered/api/entity/living/monster/Wither.java
src/main/java/org/spongepowered/api/entity/projectile/Arrow.java
src/main/java/org/spongepowered/api/entity/projectile/DamagingProjectile.java
src/main/java/org/spongepowered/api/entity/projectile/Egg.java
src/main/java/org/spongepowered/api/entity/projectile/EnderPearl.java
src/main/java/org/spongepowered/api/entity/projectile/Snowball.java
src/main/java/org/spongepowered/api/entity/projectile/explosive/WitherSkull.java
src/main/java/org/spongepowered/api/entity/projectile/explosive/fireball/Fireball.java
src/main/java/org/spongepowered/api/entity/projectile/explosive/fireball/LargeFireball.java
src/main/java/org/spongepowered/api/entity/vehicle/minecart/TNTMinecart.java
src/main/java/org/spongepowered/api/event/SpongeEventFactory.java
src/main/java/org/spongepowered/api/event/entity/explosive/DefuseExplosiveEvent.java
src/main/java/org/spongepowered/api/event/entity/explosive/DetonateExplosiveEvent.java
src/main/java/org/spongepowered/api/event/entity/explosive/PrimeExplosiveEvent.java
src/main/java/org/spongepowered/api/event/entity/explosive/TargetExplosiveEvent.java
src/main/java/org/spongepowered/api/event/entity/explosive/TargetFusedExplosiveEvent.java

[**API**](https://github.com/SpongePowered/SpongeAPI/pull/1164) | [Common](https://github.com/SpongePowered/SpongeCommon/pull/620)
[Test plugin](https://gist.github.com/windy1/adfd334770ef12c13dba9a348f9570dc)
This PR completes the Explosives API and adds two new events: `ExplosiveEntityEvent.Prime` and `ExplosiveEntityEvent.Detonate`.
Signed-off-by: Walker Crouse <walkercrouse@hotmail.com>

Rework Explosives API for implementation

---

src/main/java/org/spongepowered/api/data/DataManager.java
src/main/java/org/spongepowered/api/data/DataView.java
src/main/java/org/spongepowered/api/data/MemoryDataView.java
src/main/java/org/spongepowered/api/data/Queries.java
src/main/java/org/spongepowered/api/data/persistence/DataSerializer.java
src/test/java/org/spongepowered/api/data/MemoryDataTest.java

**SpongeAPI** | [SpongeCommon](https://github.com/SpongePowered/SpongeCommon/pull/634)
Plainly, this adds the ability for POJOs to reactively be serialized appropriately without creating `DataContainer`s for the various objects.
The default implementation in SpongeCommon contains registration for the following:
- `java.util.UUID`
- `com.flowpowered.math.vector.Vector2i`
- `com.flowpowered.math.vector.Vector2l`
- `com.flowpowered.math.vector.Vector2d`
- `com.flowpowered.math.vector.Vector2f`
- `com.flowpowered.math.vector.Vector3i`
- `com.flowpowered.math.vector.Vector3l`
- `com.flowpowered.math.vector.Vector3d`
- `com.flowpowered.math.vector.Vector3f`
- `com.flowpowered.math.vector.Vector4i`
- `com.flowpowered.math.vector.Vector4l`
- `com.flowpowered.math.vector.Vector4d`
- …

Add DataSerializer API for Java Objects not able to implement DataSerializable

---

src/main/java/org/spongepowered/api/effect/Viewer.java

[**API**](https://github.com/SpongePowered/SpongeAPI/pull/1144) | [Common](https://github.com/SpongePowered/SpongeCommon/pull/591)
This adds the ability to send block changes to `Viewer`s without actually having the block change in the world.
Resolves https://github.com/SpongePowered/SpongeAPI/issues/619

Virtual block changes

---

src/main/java/org/spongepowered/api/world/Chunk.java

Looking up chunks from the world's global chunk map is a major hotspot in the server. This API provides a means to get chunks relative to one you already have without going through this map. The default implementation still goes through the world but SpongeCommon overrides this to implement a more efficient lookup.

Add Chunk#getNeighbor API for efficiently accessing neighbor chunks

---

src/main/java/org/spongepowered/api/event/filter/Getter.java
src/main/java/org/spongepowered/api/util/generator/event/factory/ClassGenerator.java
src/main/java/org/spongepowered/api/util/generator/event/factory/plugin/AccessorModifierEventFactoryPlugin.java

Implemented by https://github.com/SpongePowered/SpongeCommon/pull/519
This PR adds an event filter for retrieving values from getters on the event type. This annotation annotates a parameter and acts as a source for the parameter value. The annotation specifies a method name which must be a method on the specified event type. The parameter's value is set to the result of calling the specified method on the event. 
Example:
```java
@Listener
public void onPlayerDamage(EntityDamageEvent event, @Getter("getTargetEntity") Player player) {
// do something with player
}
```
Here we have a Player parameter annotated with the `Getter` annotation. The value for the parameter will be the result of calling `event.getTargetEntity()`. You'll notice that the return type of getTargetEntity is `Entity` …

Add More Event Filters

---

src/main/java/org/spongepowered/api/world/gen/Populator.java
src/main/java/org/spongepowered/api/world/gen/populator/BigMushroom.java
src/main/java/org/spongepowered/api/world/gen/populator/DoublePlant.java
src/main/java/org/spongepowered/api/world/gen/populator/Flower.java
src/main/java/org/spongepowered/api/world/gen/populator/Forest.java
src/main/java/org/spongepowered/api/world/gen/populator/Mushroom.java
src/main/java/org/spongepowered/api/world/gen/populator/Shrub.java

[Forge](https://github.com/SpongePowered/SpongeForge/pull/627) | [Common](https://github.com/SpongePowered/SpongeCommon/pull/715) | Api
This makes a small change to `Populator#populate` in order to give it an extent view of the area needing population rather than relying on the plugin to offset to the correct location, this also allows much more flexibility for implementations who wish to use a different pattern for population.
A major usecase for this change is the ability to populate a non offset area to allow a single chunk to be regenerated for #574.

Change populators to take an extent for the area to be populated

---

src/main/java/org/spongepowered/api/data/key/Keys.java
src/main/java/org/spongepowered/api/data/manipulator/catalog/CatalogEntityData.java
src/main/java/org/spongepowered/api/data/manipulator/immutable/entity/ImmutableDominantHandData.java
src/main/java/org/spongepowered/api/data/manipulator/mutable/entity/DominantHandData.java
src/main/java/org/spongepowered/api/data/property/entity/DominantHandProperty.java
src/main/java/org/spongepowered/api/data/type/HandType.java
src/main/java/org/spongepowered/api/data/type/HandTypes.java

*Continuation of #1121*
SpongePowered/SpongeCommon#630
This PR adds the ability for plugins to query the handedness of entities.
Players are able to configure handedness through client settings. This is not configurable serverside, as such the implementation can get a player's handedness but will not be able to set it.
Many living entities such as Skeletons or Zombies can have a dominant hand (Ghasts, for example, cannot). This is configurable with the `LeftHanded` NBT tag.
Implementation wise this will likely only be represented by a single boolean, with each value inversely toggling the it.

Add API for handedness

---

src/main/java/org/spongepowered/api/data/key/Keys.java
src/main/java/org/spongepowered/api/data/manipulator/catalog/CatalogEntityData.java
src/main/java/org/spongepowered/api/data/manipulator/immutable/entity/ImmutableGlowingData.java
src/main/java/org/spongepowered/api/data/manipulator/mutable/entity/GlowingData.java

*Continuation of #1121*
Spectral arrows can give an entity glow potion effect temporarily. You can also apply it permanently with `Glowing` NBT tag. This exposes this to SpongeAPI.
I've added a TODO in one of the javadocs - basically a couple entities do not show the glow, will need to do some testing when possible to work out exactly which entities do not do this.

Add glowing API

---

src/main/java/org/spongepowered/api/util/Direction.java
src/main/java/org/spongepowered/api/world/Location.java
src/main/java/org/spongepowered/api/world/storage/ChunkLayout.java

Fixes #1291
Common https://github.com/SpongePowered/SpongeCommon/pull/822
Forge https://github.com/SpongePowered/SpongeForge/pull/722
@bloodmc 
Output should now be correct:
> acee world.getLocation(0, 0, 0).getBlockRelative(Direction.SOUTHEAST)
[13:50:15] [Server thread/INFO]: [ACE] Type: org.spongepowered.api.world.Location<CAP#1 extends org.spongepowered.api.world.extent.Extent> Value: Location{(1.0, 0.0, 1.0) in net.minecraft.world.WorldServer@1fafeaa9}
> acee world.getLocation(0, 0, 0).getRelative(Direction.SOUTHEAST)
[13:50:33] [Server thread/INFO]: [ACE] Type: org.spongepowered.api.world.Location<CAP#1 extends org.spongepowered.api.world.extent.Extent> Value: Location{(0.7071067811865475, 0.0, 0.7071067811865475) in net.minecraft.world.WorldServer@1fafeaa9}

Add support for ordinal block offsets in Direction

---

src/main/java/org/spongepowered/api/block/BlockSnapshot.java
src/main/java/org/spongepowered/api/data/value/mutable/CompositeValueStore.java
src/main/java/org/spongepowered/api/extra/modifier/skylands/SkylandsGrassPopulator.java
src/main/java/org/spongepowered/api/extra/modifier/skylands/SkylandsGroundCoverPopulator.java
src/main/java/org/spongepowered/api/extra/modifier/skylands/SkylandsTerrainGenerator.java
src/main/java/org/spongepowered/api/world/BlockChangeFlag.java
src/main/java/org/spongepowered/api/world/Chunk.java
src/main/java/org/spongepowered/api/world/Location.java
src/main/java/org/spongepowered/api/world/World.java
src/main/java/org/spongepowered/api/world/extent/BlockVolume.java
src/main/java/org/spongepowered/api/world/extent/Extent.java
src/main/java/org/spongepowered/api/world/extent/ImmutableBlockVolume.java
src/main/java/org/spongepowered/api/world/extent/InteractableVolume.java
src/main/java/org/spongepowered/api/world/extent/LocationCompositeValueStore.java
src/main/java/org/spongepowered/api/world/extent/MutableBlockVolume.java
src/main/java/org/spongepowered/api/world/extent/TileEntityVolume.java
src/main/java/org/spongepowered/api/world/extent/UnmodifiableBlockVolume.java
src/main/java/org/spongepowered/api/world/extent/worker/BlockVolumeWorker.java
src/main/java/org/spongepowered/api/world/extent/worker/MutableBlockVolumeWorker.java
src/main/java/org/spongepowered/api/world/gen/Populator.java

**SpongeAPI** | [SpongeCommon](https://github.com/SpongePowered/SpongeCommon/pull/851) | [SpongeForge](https://github.com/SpongePowered/SpongeForge/pull/770)
This is a more focused PR at dealing with several issues at once, but for the sake of having not had a decent PR description in a while, I'll rehash the conversational description that we used to have a while back.
In short, if a plugin developer is calling any API method that changes something, an event should be thrown. Traditionally, we used to have the inability to throw events for virtually everything, however, at this point in time, it's well within our means to throw events for all `setBlock`, `createEntity`, `spawnEntity`, etc. 
Yes and no. It's been useful for developers to throw "dummy" events to check for permissions or …

Refactor Block Change API

---

src/main/java/org/spongepowered/api/event/cause/entity/damage/source/common/AbstractEntityDamageSource.java
src/main/java/org/spongepowered/api/event/cause/entity/damage/source/common/AbstractIndirectEntityDamageSource.java

This following example is currently impossible to make, you have to insert the builder interface type in the `AbstractEntityDamageSourceBuilder` generics, but they only allow `AbstractEntityDamageSourceBuilder`s, and the generics of the `CustomEntityDamageSource.Builder` specify that you want a `CustomEntityDamageSource.Builder` as return value. This causes a conflict and breaks the `CustomEntityDamageSourceBuilderImpl`.
This is the same case for the `AbstractIndirectEntityDamageSource`.
And exposed some fields to allow some null checks in the build method.
```java
public interface CustomEntityDamageSource extends EntityDamageSource {
public interface Builder extends EntityDamageSource.EntityDamageSourceBuilder<CustomEntityDamageSource, Builder> {
}
}
```
```java
public class …
```

Fix Abstract(Indirect)EntityDamageSource generics and expose some fields.

---

build.gradle
src/main/java/org/spongepowered/api/data/key/Keys.java
src/main/java/org/spongepowered/api/data/manipulator/immutable/entity/ImmutablePickupRuleData.java
src/main/java/org/spongepowered/api/data/manipulator/mutable/entity/PickupRuleData.java
src/main/java/org/spongepowered/api/data/type/PickupRule.java
src/main/java/org/spongepowered/api/data/type/PickupRules.java

[**API**](https://github.com/SpongePowered/SpongeAPI/pull/1218) | [Common](https://github.com/SpongePowered/SpongeCommon/pull/693)
Supersedes #1193 
This adds an API to control an `Arrow`s pickup rule.

Arrow pickup rules

---

build.gradle

Since we now bundle [Caffeine](https://github.com/ben-manes/caffeine) with SpongeCommon we can also expose it to plugins so they can use it without having to bundle it together with the plugin.
Additional to Caffeine I've also added the Guava adaptors which may be useful for some plugins that are still using Guava caches right now.

Expose Caffeine to plugins

---

src/ap/java/org/spongepowered/plugin/processor/PluginElement.java
src/main/java/org/spongepowered/api/asset/AssetManager.java
src/main/java/org/spongepowered/api/plugin/Plugin.java
src/main/java/org/spongepowered/api/plugin/PluginContainer.java

The asset manager allows changing the directory where all plugin assets are stored. This was originally added for flexibility, but I can personally not see any usecases to change the asset directory. On the other hand, there are two reasons why it should **not** be changed:
- Assets in Vanilla Minecraft and Forge are always stored in the `assets/id` directory
- Changing the asset directory could cause problems with resource packs in future client-side plugins (since that requires assets to be stored in the default directory)
This PR removes the option to set custom asset directories. Unless someone has a usecase for the option I don't see any reason to keep it, since the default directory is always the best choice.

Remove custom asset directories

---

src/main/java/org/spongepowered/api/command/CommandResult.java

This adds the following helper methods to `CommandResult` to prevent lots of duplication in plugins:
- `CommandResult.successCount(int)`
- `CommandResult.affectedBlocks(int)`
- `CommandResult.affectedEntities(int)`
- `CommandResult.affectedItems(int)`
- `CommandResult.queryResult(int)`

Add helper methods to CommandResult

---

src/main/java/org/spongepowered/api/command/spec/CommandSpec.java

add child(CommandCallable, Collection<String>):CommandSpec.Builder to CommandSpec.Builder. This is simply a utility method.

add child(CommandCallable, Collection<String>) utility method

---

src/main/java/org/spongepowered/api/asset/Asset.java

My attempt at fixing https://github.com/SpongePowered/SpongeAPI/issues/1255
Add Asset::copyToDirectory that copies the asset (using it's filename ignoring path) to the provided directory.
Add Asset::getFileName to get the filename portion of the url.

add Asset::copyToDirectory and Asset::getFileName

---

src/main/java/org/spongepowered/api/world/biome/BiomeGenerationSettings.java
src/main/java/org/spongepowered/api/world/biome/BiomeType.java
src/main/java/org/spongepowered/api/world/biome/VirtualBiomeType.java
src/main/java/org/spongepowered/api/world/gen/Populator.java

**SpongeAPI** | [SpongeCommon](https://github.com/SpongePowered/SpongeCommon/pull/928) | [SpongeForge](https://github.com/SpongePowered/SpongeForge/pull/900)
This adds support for creating custom biomes which exist only during generation, afterwards they are stored as an existing non-virtual biome. This can be used to support more varied generation easier without creating full blown custom biomes which would require client modifications as well.

Add support for virtual custom biomes

---

src/ap/java/org/spongepowered/plugin/processor/PluginElement.java
src/main/java/org/spongepowered/api/Platform.java

Using these changes the annotation processor will add a required dependency on SpongeAPI which allows identifying Sponge plugins based on their `mcmod.info` file.
The dependency version is set to the SpongeAPI version the plugin is compiled against. Without additional restrictions the dependency version will just represent the "recommended version" for the dependency.
While plugins will continue to load using newer or older API versions, these changes allow the implementation to issue a warning if a plugin was designed for an older or newer API version.
SpongeVanilla implementation: https://github.com/SpongePowered/SpongeVanilla/pull/269
SpongeForge implementation: https://github.com/SpongePowered/SpongeForge/pull/907
**Note:** This is similar to …

Add required dependency on SpongeAPI for plugins

---

src/main/java/org/spongepowered/api/data/key/Keys.java
src/main/java/org/spongepowered/api/data/manipulator/catalog/CatalogEntityData.java
src/main/java/org/spongepowered/api/data/manipulator/immutable/entity/ImmutableGravityData.java
src/main/java/org/spongepowered/api/data/manipulator/mutable/entity/ArmorStandData.java
src/main/java/org/spongepowered/api/data/manipulator/mutable/entity/GravityData.java
src/main/java/org/spongepowered/api/entity/Entity.java
src/main/java/org/spongepowered/api/entity/living/ArmorStand.java

**[API](https://github.com/SpongePowered/SpongeAPI/pull/1301)** | [Common](https://github.com/SpongePowered/SpongeCommon/pull/828)
Adds `GravityData` and removes gravity from `ArmorStandData`. This is due to a change in Minecraft  1.10 that allows all entities, not just armor stands, to be affected by the `NoGravity` tag.
Resolves #1300. 
```java
@Listener
public void onPlayerJoin(ClientConnectionEvent.Join event) {
Player player = event.getTargetEntity();
// Prints the current value
System.out.println(player.get(Keys.ENTITY_HAS_GRAVITY).get());
// Turns off gravity for the player
player.offer(Keys.ENTITY_HAS_GRAVITY, false);
// Test the DataManipulator
Optional<GravityData> optional = player.get(GravityData.class);
if(optional.isPresent()) {
Value<Boolean> value = …
```

Added GravityData and removed gravity from ArmorStandData

---

src/main/java/org/spongepowered/api/command/args/GenericArguments.java

@zml2008 @mcmonkey4eva 
@mcmonkey4eva mentioned in IRC that remainingJoinedStrings still had some form of processing being applied, @zml2008 said that there was already a raw option exposed.
I looked, saw that it was limited to private visibility, presumably because it was added later and not thought about.

Expose RemainingJoinedStrings raw mode.

---

src/main/java/org/spongepowered/api/command/args/GenericArguments.java
src/main/java/org/spongepowered/api/util/blockray/BlockRay.java

In response to: https://github.com/SpongePowered/SpongeAPI/pull/1342
This adds a `skipFilter` to ignore blocks that match a predicate. The previous filter functionality gets renamed to `stopFilter`.
Also, based off of feedback from @Deamon5550, I changed the block limit into a distance limit. Since the filter is now built-in it was removed as a stand-alone.
Finally I fixed the `GenericArguments` `#target` functionality not returning the target block, but the air block just before it. 
I've fixed Cookbook/Smite and I'll merge those changes if the PR is accepted.
@m0pt0pmatt

Improve the block ray filters

---

src/main/java/org/spongepowered/api/network/ChannelRegistrar.java

You can now query for existing channels.
A convenience method `getOrCreate` and `getOrCreateRaw` have also been added
Example use for bungeecord
```java
RawDataChannel bungeeChannel = Sponge.getChannelRegistrar().getOrCreateRaw(this, "BungeeCord");
```
Side node: modifications to SpongeForge/SpongeVanilla are trivial so I'll update them if this PR is merged

Add methods to ChannelRegistrar for getting existing channels

---

src/main/java/org/spongepowered/api/data/key/Keys.java
src/main/java/org/spongepowered/api/data/manipulator/catalog/CatalogEntityData.java
src/main/java/org/spongepowered/api/data/manipulator/immutable/entity/ImmutableZombieData.java
src/main/java/org/spongepowered/api/data/manipulator/mutable/entity/ZombieData.java
src/main/java/org/spongepowered/api/data/type/ZombieType.java
src/main/java/org/spongepowered/api/data/type/ZombieTypes.java

This changes VillagerZombieData to a composite DataManipulator.
The ZombieType specifies the kind of zombie, with Optional<Profession> specifying the profession only if it's a villager zombie.
This system allows mods to add new types of zombie villagers without requiring a matching zombie type (as is the current vanilla implementation).

Update ZombieData for 1.10 features

---

src/main/java/org/spongepowered/api/service/permission/PermissionService.java
src/main/java/org/spongepowered/api/service/permission/Subject.java
src/main/java/org/spongepowered/api/service/permission/SubjectCollection.java
src/main/java/org/spongepowered/api/service/permission/SubjectData.java

This PR attempts to clarify some of the ambiguities in PermissionService, as raised in #1383.
As far as I know, the added javadocs do not conflict with existing intended behaviours, rather just clarifies them. 
Possibly relevant: some of the issues were also briefly discussed here: https://forums.spongepowered.org/t/luckperms-an-advanced-permissions-system/14274/118

Clarify some parts of the PermissionService documentation

---

src/main/java/org/spongepowered/api/command/args/GenericArguments.java
src/main/java/org/spongepowered/api/command/spec/CommandSpec.java
src/main/java/org/spongepowered/api/data/DataSerializable.java
src/main/java/org/spongepowered/api/data/key/Keys.java
src/main/java/org/spongepowered/api/effect/potion/PotionEffectTypes.java
src/main/java/org/spongepowered/api/event/server/query/QueryServerEvent.java
src/main/java/org/spongepowered/api/item/inventory/ItemStack.java
src/main/java/org/spongepowered/api/item/inventory/equipment/EquipmentTypes.java
src/main/java/org/spongepowered/api/item/inventory/property/AcceptsItems.java
src/main/java/org/spongepowered/api/item/inventory/type/TileEntityInventory.java
src/main/java/org/spongepowered/api/network/ChannelBuf.java
src/main/java/org/spongepowered/api/service/permission/option/OptionSubjectData.java
src/main/java/org/spongepowered/api/statistic/StatisticFormat.java
src/main/java/org/spongepowered/api/util/Direction.java
src/main/java/org/spongepowered/api/world/ChunkTicketManager.java
src/main/java/org/spongepowered/api/world/World.java
src/main/java/org/spongepowered/api/world/gen/populator/Lake.java
src/main/java/org/spongepowered/api/world/storage/WorldStorage.java

"OCD" JDoc fixes. DataHolder already extends DataSerializable.

Fixes JavaDoc issues in #1000; removes implements DataSerializable from ItemStack

---

src/main/java/org/spongepowered/api/effect/sound/SoundType.java

**API** | [Common](https://github.com/SpongePowered/SpongeCommon/pull/955) | [Forge](https://github.com/SpongePowered/SpongeForge/pull/923)
Currently if a developer wants to send a custom `SoundType` (such as one from a mod or resource pack) they must implement their own `SoundType`. While small, this changes it to instead be a builder so developers can rely on common to create an instance of `SoundEvent` (the NMS impl) for them.

Add SoundType builder

---

src/main/java/org/spongepowered/api/block/tileentity/MobSpawner.java
src/main/java/org/spongepowered/api/data/key/Keys.java
src/main/java/org/spongepowered/api/data/manipulator/immutable/ImmutableMobSpawnerData.java
src/main/java/org/spongepowered/api/data/manipulator/mutable/MobSpawnerData.java
src/main/java/org/spongepowered/api/entity/EntityArchetype.java
src/main/java/org/spongepowered/api/util/weighted/UnmodifiableWeightedTable.java
src/main/java/org/spongepowered/api/world/gen/populator/Dungeon.java

**API** | [Common](https://github.com/SpongePowered/SpongeCommon/pull/710) | [Forge](https://github.com/SpongePowered/SpongeForge/pull/794)
Changes `MobSpawnerData` and `Dungeon` to use `EntityArchetype`s instead of `EntitySnapshot`s.
Updates `Dungeon` to have option of a table, as explained in the Common branch.
Adds a convenience method to `EntityArchetype` for creating an archetype based solely on an `EntityType`.
Also adds an immutable/unmodifiable version of `WeightedTable` to allow for wrapping of the default list of entities to use in a Dungeon. Without this, plugins could add/remove from this list potentially causing issues down the line. (if this is desired, maybe need to add better systems for doing so?)

Update MobSpawnerData for Archetypes

---

src/main/java/org/spongepowered/api/event/SpongeEventFactory.java
src/main/java/org/spongepowered/api/event/entity/ChangeEntityPotionEffectEvent.java

This targets bleeding because the existing getPotionEffect() method would return the changed effect, and does not currently.

Make the potion effect in ChangeEntityPotionEffect.Gain mutable

---

src/main/java/org/spongepowered/api/event/SpongeEventFactory.java
src/main/java/org/spongepowered/api/event/entity/RideEntityEvent.java

API | [Common](https://github.com/SpongePowered/SpongeCommon/pull/944)
The event RideEntityEvent.Dismount doesn't use DismountType

Add DismountType to RideEntityEvent.Dismount

---

src/main/java/org/spongepowered/api/entity/living/player/Player.java

[API](https://github.com/SpongePowered/SpongeAPI/pull/1283) | [Common](https://github.com/SpongePowered/SpongeCommon/pull/895)
This PR adds a method to Player, that allows for the simulation of chat.
The exact reasoning of it can be seen in the corresponding issue, https://github.com/SpongePowered/SpongeAPI/issues/733
This method returns the event so that the plugin can see what modifications have been made by other plugins, and to see if it has been cancelled.
Test code,
``` java
@Listener
public void onInteract(InteractBlockEvent.Secondary event, @First Player player) {
player.simulateChat(Text.of("Hello there"));
}
@Listener
public void onMessage(MessageChannelEvent.Chat chat, @First Player player) {
Sponge.getServer().getBroadcastChannel().send(Text.of("Hello, " + player.getName() + …
```

Added Player chat simulation method. Adds #733

---

src/main/java/org/spongepowered/api/world/World.java

Since both our implementations support asynchronous chunk loading now we should allow plugins to use that feature by being able to load chunks asynchronously if they don't need the loaded chunk immediately.
**Implementation:** [SpongeVanilla](https://github.com/SpongePowered/SpongeVanilla/pull/303) |  [SpongeForge](https://github.com/SpongePowered/SpongeForge/pull/1299)

Allow plugins to load chunks asynchronously

---

src/main/java/org/spongepowered/api/command/spec/CommandSpec.java

Basically a Quality of Life thing, I guess. I found it annoying that the only way to access the `extendedDescription` for a `CommandSpec` was from the `getHelp` method, and as such worked this up.
(Previously, was adding it to the `CommandCallable` interface, but @kashike redirected me to just implement it for the `CommandSpec` class.)

Add `getExtendedDescription` to the `CommandSpec` class.
