src/main/java/org/spongepowered/api/world/WorldBorder.java
Added method to start, end, time the world border. 
Changed radius to diameter.
Changed blockbuffer to buffer as it is not measured in blocks.
=> World Border Changes.

src/main/java/org/spongepowered/api/event/SpongeEventFactory.java
This adds factories for creating subclasses of `PlayerFishEvent`
=> Add fishing event factories

src/main/java/org/spongepowered/api/event/SpongeEventFactory.java, src/main/java/org/spongepowered/api/event/block/BlockHarvestEvent.java, src/main/java/org/spongepowered/api/event/entity/EntityBreakBlockEvent.java, src/main/java/org/spongepowered/api/event/entity/EntityHarvestBlockEvent.java, src/main/java/org/spongepowered/api/event/entity/living/LivingHarvestBlockEvent.java, src/main/java/org/spongepowered/api/event/entity/living/human/HumanHarvestBlockEvent.java, src/main/java/org/spongepowered/api/event/entity/living/player/PlayerHarvestBlockEvent.java
I have created a new event, `BlockHarvestEvent` see the javadoc. 
This is the result from a previous PR, #422
=> Add BlockHarvestEvent, changes how silk touch enchant works

src/main/java/org/spongepowered/api/entity/Entity.java, src/main/java/org/spongepowered/api/event/SpongeEventFactory.java, src/main/java/org/spongepowered/api/event/entity/EntityDisplacementEvent.java, src/main/java/org/spongepowered/api/event/entity/EntityTeleportEvent.java
Also adds further hierarchy with EntityDisplacementEvent.
The EntityDisplacementEvent is now considered as an event when an entity can be teleported or moved. The EntityMoveEvent includes information regarding previous velocity and the new velocity.
=> Add Velocity to Entities

src/main/java/org/spongepowered/api/util/InformativeMain.java
This creates a JOptionPane for those that are trying to launch the binary jar from desktop.
=> Use a JOptionPane if we have GUI.

src/main/java/org/spongepowered/api/util/blockray/BlockRay.java
=> Fix build on Apple JDK 6

src/main/java/org/spongepowered/api/Server.java, src/main/java/org/spongepowered/api/world/storage/WorldProperties.java
Add methods to delete an unloaded World, as well as a method to retrieve the folder for a World.
=> Additional API for World Management

src/main/java/org/spongepowered/api/world/Location.java
Simply allows for the ability to subtract from a Location because it was requested
=> Added location.sub() to subtract from Locations

src/main/java/org/spongepowered/api/data/key/Keys.java, src/main/java/org/spongepowered/api/data/manipulator/immutable/item/ImmutableHideData.java, src/main/java/org/spongepowered/api/data/manipulator/mutable/item/HideData.java
Added the HideData manipulator, the corresponding keys, and the Immutable version of the manipulator.
Adds https://github.com/SpongePowered/SpongeAPI/issues/905
=> Added HideData, and corresponding keys. Adds #905

src/main/java/org/spongepowered/api/data/type/SkinPart.java, src/main/java/org/spongepowered/api/data/type/SkinParts.java, src/main/java/org/spongepowered/api/entity/living/player/Player.java, src/main/java/org/spongepowered/api/event/SpongeEventFactory.java, src/main/java/org/spongepowered/api/event/entity/living/humanoid/player/PlayerChangeClientSettingsEvent.java, src/main/java/org/spongepowered/api/text/chat/ChatVisibilities.java, src/main/java/org/spongepowered/api/text/chat/ChatVisibility.java, src/test/java/org/spongepowered/api/event/SpongeEventFactoryTest.java
=> Add PlayerChangeSettingsEvent, resolves #786

src/main/java/org/spongepowered/api/effect/Viewer.java, src/main/java/org/spongepowered/api/entity/living/player/Player.java, src/main/java/org/spongepowered/api/text/channel/AbstractMutableMessageChannel.java, src/main/java/org/spongepowered/api/text/channel/ChatTypeMessageReceiver.java, src/main/java/org/spongepowered/api/text/channel/MessageChannel.java, src/main/java/org/spongepowered/api/text/channel/impl/DelegateMessageChannel.java, src/main/java/org/spongepowered/api/text/channel/impl/SimpleMutableMessageChannel.java, src/main/java/org/spongepowered/api/world/World.java
[**API**](https://github.com/SpongePowered/SpongeAPI/pull/1043) | [Common](https://github.com/SpongePowered/SpongeCommon/pull/445) | [Forge](https://github.com/SpongePowered/SpongeForge/pull/523) | [Vanilla](https://github.com/SpongePowered/SpongeVanilla/pull/221)
=> Add ChatType methods to MessageChannel

src/main/java/org/spongepowered/api/data/key/Keys.java, src/main/java/org/spongepowered/api/data/manipulator/immutable/entity/ImmutableRespawnLocation.java, src/main/java/org/spongepowered/api/data/manipulator/mutable/entity/RespawnLocationData.java, src/main/java/org/spongepowered/api/entity/living/player/RespawnLocation.java
#961 on the bleeding edge
Changes `Vector3d` to `Tuple<Vector3d, Boolean>`
See #955
=> Add ability to get/set forced bed location. Resolves #955

src/main/java/org/spongepowered/api/text/format/TextFormat.java
`TextFormat` is missing methods to create it.
=> Add methods to create TextFormat

src/main/java/org/spongepowered/api/command/args/GenericArguments.java
userOrSource behaves like playerOrSource
=> Add userOrSource to GenericArguments

src/main/java/org/spongepowered/api/command/CommandCallable.java
=> Switch CommandCallable methods to return Optional<Text>

src/main/java/org/spongepowered/api/Server.java
[**API**](https://github.com/SpongePowered/SpongeAPI/pull/1232) | [Common](https://github.com/SpongePowered/SpongeCommon/pull/716)
=> Add getter and setter for player idle timeout to Server

src/main/java/org/spongepowered/api/text/channel/ChatTypeMessageReceiver.java, src/main/java/org/spongepowered/api/text/channel/MessageChannel.java, src/main/java/org/spongepowered/api/text/channel/MessageReceiver.java, src/main/java/org/spongepowered/api/text/channel/impl/DelegateMessageChannel.java, src/main/java/org/spongepowered/api/text/channel/type/CombinedMessageChannel.java, src/main/java/org/spongepowered/api/text/channel/type/FixedMessageChannel.java, src/main/java/org/spongepowered/api/text/channel/type/WorldMessageChannel.java, src/main/java/org/spongepowered/api/world/World.java
[**API**](https://github.com/SpongePowered/SpongeAPI/pull/1202) | [Common](https://github.com/SpongePowered/SpongeCommon/pull/676)
=> World is a MessageReceiver, add TextTemplate methods to ChatTypeMessageReceiver, and add WorldMessageChannel

build.gradle, src/main/java/org/spongepowered/api/boss/BossBar.java, src/main/java/org/spongepowered/api/boss/BossBarColor.java, src/main/java/org/spongepowered/api/boss/BossBarColors.java, src/main/java/org/spongepowered/api/boss/BossBarOverlay.java, src/main/java/org/spongepowered/api/boss/BossBarOverlays.java, src/main/java/org/spongepowered/api/boss/ServerBossBar.java, src/main/java/org/spongepowered/api/boss/package-info.java
[**API**](https://github.com/SpongePowered/SpongeAPI/pull/1217) | [Common](https://github.com/SpongePowered/SpongeCommon/pull/692)
Supersedes #1149 
Adds #728 
Example:
```java
@Listener
public void join(final ClientConnectionEvent.Join event) {
Player player = event.getTargetEntity();
ServerBossBar bossBarA = ServerBossBar.builder()
.name(Text.of(
TextColors.DARK_AQUA, "A",
TextColors.DARK_PURPLE, "l",
TextColors.BLUE, "l",
" ",
TextColors.DARK_GREEN, "y",
TextColors.AQUA, "o",
TextColors.RED, "u",
TextColors.LIGHT_PURPLE, "r",
" ",
TextColors.GOLD, "c",
TextColors.DARK_AQUA, "o",
TextColors.LIGHT_PURPLE, "l",
TextColors.DARK_PURPLE, "o",
TextColors.DARK_GREEN, "r",
TextColors.RED, "s",
" ",
TextColors.GOLD, "s",
TextColors.DARK_GREEN, "t",
TextColors.DARK_PURPLE, "a", …
```
=> Boss Bar API

src/main/java/org/spongepowered/api/profile/GameProfileCache.java
[**API**](https://github.com/SpongePowered/SpongeAPI/pull/1244) | [Common](https://github.com/SpongePowered/SpongeCommon/pull/720)
=> Add removal and clear methods to GameProfileCache

build.gradle, src/main/java/org/spongepowered/api/scoreboard/CollisionRule.java, src/main/java/org/spongepowered/api/scoreboard/CollisionRules.java, src/main/java/org/spongepowered/api/scoreboard/Team.java
[**API**](https://github.com/SpongePowered/SpongeAPI/pull/1219) | [Common](https://github.com/SpongePowered/SpongeCommon/pull/694)
Supersedes #1154
=> Add collision rules to scoreboard API

src/main/java/org/spongepowered/api/world/gamerule/DefaultGameRules.java
This adds the new 1.9 gamerules, and adds a [description](http://minecraft.gamepedia.com/Commands#gamerule) to all gamerules.
Supersedes #1187
=> Add new 1.9 gamerules, and add a description to all gamerules

src/main/java/org/spongepowered/api/block/tileentity/EndGateway.java, src/main/java/org/spongepowered/api/block/tileentity/Structure.java, src/main/java/org/spongepowered/api/data/key/Keys.java, src/main/java/org/spongepowered/api/data/manipulator/immutable/tileentity/ImmutableEndGatewayData.java, src/main/java/org/spongepowered/api/data/manipulator/immutable/tileentity/ImmutableStructureData.java, src/main/java/org/spongepowered/api/data/manipulator/immutable/tileentity/package-info.java, src/main/java/org/spongepowered/api/data/manipulator/mutable/tileentity/EndGatewayData.java, src/main/java/org/spongepowered/api/data/manipulator/mutable/tileentity/StructureData.java, src/main/java/org/spongepowered/api/data/type/StructureMode.java, src/main/java/org/spongepowered/api/data/type/StructureModes.java
[**API**](https://github.com/SpongePowered/SpongeAPI/pull/1216) | [Common](https://github.com/SpongePowered/SpongeCommon/pull/691)
Supersedes #1146
=> Add new 1.9 block entities

src/main/java/org/spongepowered/api/world/extent/EntityUniverse.java
API | [Common](https://github.com/SpongePowered/SpongeCommon/pull/923)
To fix conflicts, I recreated a new branch.
=> [Update] Adding a method to create an entity naturally

src/main/java/org/spongepowered/api/entity/living/Humanoid.java, src/main/java/org/spongepowered/api/entity/living/Living.java, src/main/java/org/spongepowered/api/entity/living/Ranger.java, src/main/java/org/spongepowered/api/entity/living/animal/Llama.java, src/main/java/org/spongepowered/api/entity/living/complex/EnderDragon.java, src/main/java/org/spongepowered/api/entity/living/monster/Ghast.java, src/main/java/org/spongepowered/api/entity/projectile/ProjectileLauncher.java
[**API**](https://github.com/SpongePowered/SpongeAPI/pull/1227) | [Common](https://github.com/SpongePowered/SpongeCommon/pull/711)
Fixes #1097
=> All living entities are a Projectile source

src/main/java/org/spongepowered/api/data/persistence/DataFormats.java
**API** | [Common](https://github.com/SpongePowered/SpongeCommon/pull/1299)
=> Add JSON DataFormat. Fixes #1047
